name: tabnet
n_d: 64
n_a: 64
n_steps: 5
gamma: 1.5
cat_emb_dim: 1
n_independent: 2
n_shared: 2
epsilon: 1.0e-15
virtual_batch_size: 128
momentum: 0.3
lambda_sparse: 0.001
mask_type: entmax
learning_rate: 0.02
weight_decay: 0.0
batch_size: 1024
epochs: 100
optimizer_name: adam
clip_grad_norm: 1.0
drop_last: true
model_family: tabnet
